// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateLicense(arg1:string):Promise<main.LicenseResponse>;

export function AnalyzeRomSource(arg1:string):Promise<main.RomSourceAnalysis>;

export function CancelBackup():Promise<void>;

export function CancelExtract():Promise<void>;

export function CancelFlash():Promise<void>;

export function CancelRestore():Promise<void>;

export function ChangeLibraryPath():Promise<string>;

export function CheckDevice():Promise<main.DeviceInfo>;

export function CheckDeviceSpace(arg1:number):Promise<boolean>;

export function CheckDiskSpace(arg1:number):Promise<boolean>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CheckLicenseOnInit():Promise<void>;

export function CheckRootAccess():Promise<boolean>;

export function CopyFromCache(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteFlashReport(arg1:string):Promise<void>;

export function DeleteLibraryItem(arg1:string):Promise<void>;

export function DetectRootCapabilities():Promise<main.RootCapabilityReport>;

export function DispatchFlashByBrand(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function ExportLatestFlashReport():Promise<string>;

export function ExtractFromPayload(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function ExtractPartitions(arg1:main.ExtractRequest):Promise<void>;

export function FlashImagesSmartGroup(arg1:Array<main.PartitionItem>):Promise<void>;

export function FlashOnePlusROM(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;

export function FlashPixelROM(arg1:string,arg2:boolean):Promise<void>;

export function FlashXiaomiROM(arg1:string,arg2:boolean):Promise<void>;

export function GetBackupEstimatedSize():Promise<number>;

export function GetBackupsDiskUsage():Promise<number>;

export function GetDiskFreeSpace():Promise<number>;

export function GetFlashReportDetail(arg1:string):Promise<main.FlashReport>;

export function GetFlashReports():Promise<Array<main.FlashReportSummary>>;

export function GetHWID():Promise<string>;

export function GetInstalledApps():Promise<Array<main.AppPackage>>;

export function GetLibraryList():Promise<Array<main.LibraryItem>>;

export function GetRomBoardName(arg1:string):Promise<string>;

export function GetToolPath(arg1:string):Promise<string>;

export function HandleRE4HExpiry():Promise<void>;

export function InstallDrivers():Promise<string>;

export function IsFastbootD():Promise<boolean>;

export function IsFreeMode():Promise<boolean>;

export function IsLicenseCacheValid():Promise<boolean>;

export function IsLicenseValid():Promise<boolean>;

export function IsLicenseValidForFlash():Promise<boolean>;

export function ListBackups():Promise<Array<main.BackupItem>>;

export function ListPayloadPartitions(arg1:string):Promise<Array<main.PartitionInfo>>;

export function ListRomPartitions(arg1:string):Promise<Array<main.PartitionInfo>>;

export function LoadLicenseCache():Promise<main.LicenseCacheEntry>;

export function LockBootloader():Promise<void>;

export function NotifyUI(arg1:string,arg2:string):Promise<void>;

export function OpenBrowserToDownload():Promise<void>;

export function OpenLibraryFolder(arg1:string):Promise<void>;

export function PauseDeviceWatcher():Promise<void>;

export function Ping():Promise<string>;

export function RebootBootloader():Promise<void>;

export function RebootFastbootD():Promise<void>;

export function RebootRecovery():Promise<void>;

export function RebootSystem():Promise<void>;

export function RenameLibraryItem(arg1:string,arg2:string):Promise<void>;

export function RestorePackage(arg1:string):Promise<string>;

export function ResumeDeviceWatcher():Promise<void>;

export function RunCommandReturnOutput(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function RunCommandStreaming(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RunCommandWithDir(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RunCommandWithDirUnlocked(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RunFastboot(arg1:Array<string>):Promise<void>;

export function SaveLicenseCache(arg1:main.LicenseResponse):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectImageFiles():Promise<Array<string>>;

export function SelectOutputDirectory():Promise<string>;

export function SelectRomFile():Promise<string>;

export function SelectRomFolder():Promise<string>;

export function SetDeviceBrand(arg1:string):Promise<void>;

export function SetRomTag(arg1:string,arg2:string):Promise<void>;

export function StartFlashReal(arg1:string,arg2:boolean,arg3:string,arg4:boolean,arg5:boolean):Promise<void>;

export function StartFullBackup():Promise<void>;

export function StartRestore(arg1:string):Promise<void>;

export function StartSelectiveBackup(arg1:main.BackupSelectionOptions):Promise<void>;

export function StartSelectiveRestore(arg1:string,arg2:main.RestoreOptions):Promise<void>;

export function SwitchMode(arg1:string):Promise<string>;

export function SwitchToBootloader():Promise<void>;

export function SwitchToFastbootD():Promise<void>;

export function UninstallPackage(arg1:string):Promise<string>;

export function UnlockBootloader():Promise<void>;

export function UpdateProgress(arg1:number,arg2:string):Promise<void>;

export function ValidateBackup(arg1:string):Promise<main.BackupMetadata>;

export function VerifyBackupChecksum(arg1:string):Promise<void>;

export function VerifyRomFile(arg1:string):Promise<boolean>;

export function WipeDataSafe():Promise<void>;
