// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function AnalyzeRomSource(arg1) {
  return window['go']['main']['App']['AnalyzeRomSource'](arg1);
}

export function CancelBackup() {
  return window['go']['main']['App']['CancelBackup']();
}

export function CancelExtract() {
  return window['go']['main']['App']['CancelExtract']();
}

export function CancelFlash() {
  return window['go']['main']['App']['CancelFlash']();
}

export function CancelRestore() {
  return window['go']['main']['App']['CancelRestore']();
}

export function ChangeLibraryPath() {
  return window['go']['main']['App']['ChangeLibraryPath']();
}

export function CheckDevice() {
  return window['go']['main']['App']['CheckDevice']();
}

export function CheckDeviceSpace(arg1) {
  return window['go']['main']['App']['CheckDeviceSpace'](arg1);
}

export function CheckDiskSpace(arg1) {
  return window['go']['main']['App']['CheckDiskSpace'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckLicenseOnInit() {
  return window['go']['main']['App']['CheckLicenseOnInit']();
}

export function CheckRootAccess() {
  return window['go']['main']['App']['CheckRootAccess']();
}

export function CopyFromCache(arg1, arg2, arg3) {
  return window['go']['main']['App']['CopyFromCache'](arg1, arg2, arg3);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteFlashReport(arg1) {
  return window['go']['main']['App']['DeleteFlashReport'](arg1);
}

export function DeleteLibraryItem(arg1) {
  return window['go']['main']['App']['DeleteLibraryItem'](arg1);
}

export function DetectRootCapabilities() {
  return window['go']['main']['App']['DetectRootCapabilities']();
}

export function DispatchFlashByBrand(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DispatchFlashByBrand'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportLatestFlashReport() {
  return window['go']['main']['App']['ExportLatestFlashReport']();
}

export function ExtractFromPayload(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractFromPayload'](arg1, arg2, arg3);
}

export function ExtractPartitions(arg1) {
  return window['go']['main']['App']['ExtractPartitions'](arg1);
}

export function FetchOnlineRoms(arg1, arg2) {
  return window['go']['main']['App']['FetchOnlineRoms'](arg1, arg2);
}

export function FlashImagesSmartGroup(arg1) {
  return window['go']['main']['App']['FlashImagesSmartGroup'](arg1);
}

export function FlashOnePlusROM(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FlashOnePlusROM'](arg1, arg2, arg3, arg4);
}

export function FlashPixelROM(arg1, arg2) {
  return window['go']['main']['App']['FlashPixelROM'](arg1, arg2);
}

export function FlashXiaomiROM(arg1, arg2) {
  return window['go']['main']['App']['FlashXiaomiROM'](arg1, arg2);
}

export function GetBackupEstimatedSize() {
  return window['go']['main']['App']['GetBackupEstimatedSize']();
}

export function GetBackupsDiskUsage() {
  return window['go']['main']['App']['GetBackupsDiskUsage']();
}

export function GetDiskFreeSpace() {
  return window['go']['main']['App']['GetDiskFreeSpace']();
}

export function GetFlashReportDetail(arg1) {
  return window['go']['main']['App']['GetFlashReportDetail'](arg1);
}

export function GetFlashReports() {
  return window['go']['main']['App']['GetFlashReports']();
}

export function GetHWID() {
  return window['go']['main']['App']['GetHWID']();
}

export function GetInstalledApps() {
  return window['go']['main']['App']['GetInstalledApps']();
}

export function GetLibraryList() {
  return window['go']['main']['App']['GetLibraryList']();
}

export function GetRomBoardName(arg1) {
  return window['go']['main']['App']['GetRomBoardName'](arg1);
}

export function GetToolPath(arg1) {
  return window['go']['main']['App']['GetToolPath'](arg1);
}

export function HandleRE4HExpiry() {
  return window['go']['main']['App']['HandleRE4HExpiry']();
}

export function InstallDrivers() {
  return window['go']['main']['App']['InstallDrivers']();
}

export function IsFastbootD() {
  return window['go']['main']['App']['IsFastbootD']();
}

export function IsLicenseCacheValid() {
  return window['go']['main']['App']['IsLicenseCacheValid']();
}

export function IsLicenseValid() {
  return window['go']['main']['App']['IsLicenseValid']();
}

export function IsLicenseValidForFlash() {
  return window['go']['main']['App']['IsLicenseValidForFlash']();
}

export function IsFreeMode() {
  return window['go']['main']['App']['IsFreeMode']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListPayloadPartitions(arg1) {
  return window['go']['main']['App']['ListPayloadPartitions'](arg1);
}

export function ListRomPartitions(arg1) {
  return window['go']['main']['App']['ListRomPartitions'](arg1);
}

export function LoadLicenseCache() {
  return window['go']['main']['App']['LoadLicenseCache']();
}

export function LockBootloader() {
  return window['go']['main']['App']['LockBootloader']();
}

export function NotifyUI(arg1, arg2) {
  return window['go']['main']['App']['NotifyUI'](arg1, arg2);
}

export function OpenBrowserToDownload() {
  return window['go']['main']['App']['OpenBrowserToDownload']();
}

export function OpenLibraryFolder(arg1) {
  return window['go']['main']['App']['OpenLibraryFolder'](arg1);
}

export function PauseDeviceWatcher() {
  return window['go']['main']['App']['PauseDeviceWatcher']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RebootBootloader() {
  return window['go']['main']['App']['RebootBootloader']();
}

export function RebootFastbootD() {
  return window['go']['main']['App']['RebootFastbootD']();
}

export function RebootRecovery() {
  return window['go']['main']['App']['RebootRecovery']();
}

export function RebootSystem() {
  return window['go']['main']['App']['RebootSystem']();
}

export function RenameLibraryItem(arg1, arg2) {
  return window['go']['main']['App']['RenameLibraryItem'](arg1, arg2);
}

export function RestorePackage(arg1) {
  return window['go']['main']['App']['RestorePackage'](arg1);
}

export function ResumeDeviceWatcher() {
  return window['go']['main']['App']['ResumeDeviceWatcher']();
}

export function RunCommandReturnOutput(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommandReturnOutput'](arg1, arg2, arg3);
}

export function RunCommandStreaming(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommandStreaming'](arg1, arg2, arg3);
}

export function RunCommandWithDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommandWithDir'](arg1, arg2, arg3);
}

export function RunCommandWithDirUnlocked(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCommandWithDirUnlocked'](arg1, arg2, arg3);
}

export function RunFastboot(arg1) {
  return window['go']['main']['App']['RunFastboot'](arg1);
}

export function SaveLicenseCache(arg1) {
  return window['go']['main']['App']['SaveLicenseCache'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectImageFiles() {
  return window['go']['main']['App']['SelectImageFiles']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SelectRomFile() {
  return window['go']['main']['App']['SelectRomFile']();
}

export function SelectRomFolder() {
  return window['go']['main']['App']['SelectRomFolder']();
}

export function SetDeviceBrand(arg1) {
  return window['go']['main']['App']['SetDeviceBrand'](arg1);
}

export function SetRomTag(arg1, arg2) {
  return window['go']['main']['App']['SetRomTag'](arg1, arg2);
}

export function StartFlashReal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartFlashReal'](arg1, arg2, arg3, arg4, arg5);
}

export function StartFullBackup() {
  return window['go']['main']['App']['StartFullBackup']();
}

export function StartRestore(arg1) {
  return window['go']['main']['App']['StartRestore'](arg1);
}

export function StartSelectiveBackup(arg1) {
  return window['go']['main']['App']['StartSelectiveBackup'](arg1);
}

export function StartSelectiveRestore(arg1, arg2) {
  return window['go']['main']['App']['StartSelectiveRestore'](arg1, arg2);
}

export function SwitchMode(arg1) {
  return window['go']['main']['App']['SwitchMode'](arg1);
}

export function SwitchToBootloader() {
  return window['go']['main']['App']['SwitchToBootloader']();
}

export function SwitchToFastbootD() {
  return window['go']['main']['App']['SwitchToFastbootD']();
}

export function UninstallPackage(arg1) {
  return window['go']['main']['App']['UninstallPackage'](arg1);
}

export function UnlockBootloader() {
  return window['go']['main']['App']['UnlockBootloader']();
}

export function UpdateProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateProgress'](arg1, arg2);
}

export function ValidateBackup(arg1) {
  return window['go']['main']['App']['ValidateBackup'](arg1);
}

export function VerifyBackupChecksum(arg1) {
  return window['go']['main']['App']['VerifyBackupChecksum'](arg1);
}

export function VerifyRomFile(arg1) {
  return window['go']['main']['App']['VerifyRomFile'](arg1);
}

export function WipeDataSafe() {
  return window['go']['main']['App']['WipeDataSafe']();
}
